/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ea6688ecd41bcf1330defbd415834ba8)
interface __BaseEnv_Env {
	INTAKE: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	GITHUB_CALLBACK_URL: "https://pandd-deployment-control-plane.gotoukenta62.workers.dev/api/auth/github/callback";
	MUSIC_ENABLED: "true";
	MUSIC_ENVIRONMENT: "production";
	MUSIC_PUBLIC_URL: "https://pandd-music.koto-thing.com/";
	MUSIC_BRIDGE_URL: "https://pandd-music.koto-thing.com/bridge.php";
	MUSIC_BRIDGE_KEY_ID: "primary";
	STAGING_DISPATCH_ENABLED: "true";
	PRODUCTION_DISPATCH_ENABLED: "true";
	GITHUB_APP_ID: "4572777";
	GITHUB_APP_INSTALLATION_ID: "153252357";
	GITHUB_REPOSITORY_ID: "1152962221";
	LOCAL_DEV_AUTH: string;
	SESSION_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_CALLBACK_URL" | "MUSIC_ENABLED" | "MUSIC_ENVIRONMENT" | "MUSIC_PUBLIC_URL" | "MUSIC_BRIDGE_URL" | "MUSIC_BRIDGE_KEY_ID" | "STAGING_DISPATCH_ENABLED" | "PRODUCTION_DISPATCH_ENABLED" | "GITHUB_APP_ID" | "GITHUB_APP_INSTALLATION_ID" | "GITHUB_REPOSITORY_ID" | "LOCAL_DEV_AUTH" | "SESSION_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET">> {}
}
