#include "presentation/EnglishTranslator.h"

#include <QHash>

namespace pandd {

EnglishTranslator::EnglishTranslator(QObject* parent) : QTranslator(parent) {}

QString EnglishTranslator::translate(const char*, const char* sourceText, const char*, int) const {
    static const QHash<QString, QString> translations{
        {"PandDから配信中のゲーム", "Games published by PandD"},
        {"ゲームカタログ", "Game Catalog"},
        {"ゲームカタログを開く", "Open Game Catalog"},
        {"インストール済みゲーム", "Installed Games"},
        {"配信ゲーム一覧", "Available Games"},
        {"← カタログ", "← Catalog"},
        {"設定", "Settings"},
        {"ツール", "Tools"},
        {"お知らせ", "Announcements"},
        {"ダウンロード", "Download"},
        {"ゲーム開始", "Launch Game"},
        {"一時停止", "Pause"},
        {"再開", "Resume"},
        {"実行中", "Running"},
        {"更新を確認中", "Checking for updates"},
        {"選択ゲームの主操作", "Primary action for selected game"},
        {"最新情報を読み込みました", "Latest information loaded"},
        {"操作エラー", "Operation Error"},
        {"準備完了", "Ready"},
        {"ゲームを起動できます", "The game is ready to launch"},
        {"ダウンロード完了", "Download Complete"},
        {"ゲームファイルの取得が完了しました", "The game files have been downloaded."},
        {"ダウンロードの確認", "Confirm Download"},
        {"一般", "General"},
        {"言語", "Language"},
        {"言語の変更は次回起動時に反映されます",
         "The language change will take effect after restarting the launcher."},
        {"ゲーム保存先", "Game Location"},
        {"参照", "Browse"},
        {"OSログイン時に自動起動", "Start when signing in"},
        {"自動起動時は最小化", "Start minimized"},
        {"閉じるボタンで通知領域へ格納", "Close to notification area"},
        {"ゲーム終了後にランチャーを表示", "Show launcher after the game exits"},
        {"速度上限", "Speed Limit"},
        {"無制限", "Unlimited"},
        {"ゲーム起動前に更新を確認", "Check for updates before launching"},
        {"他ゲーム実行中もダウンロードを継続", "Continue downloads while another game runs"},
        {"起動時にランチャー更新を確認", "Check launcher updates at startup"},
        {"ランチャー更新を自動適用", "Automatically apply launcher updates"},
        {"ダウンロード完了をOS通知", "Notify when downloads finish"},
        {"インストール完了をOS通知", "Notify when installation finishes"},
        {"エラーをOS通知", "Notify on errors"},
        {"ランチャー更新をOS通知", "Notify about launcher updates"},
        {"OS通知", "OS Notifications"},
        {"利用可能", "Available"},
        {"利用できません", "Unavailable"},
        {"現在のバージョン", "Current Version"},
        {"最新のバージョン", "Latest Version"},
        {"最終確認日時", "Last Checked"},
        {"更新内容", "Release Notes"},
        {"未確認", "Not checked"},
        {"更新情報はありません", "No update information"},
        {"必須: %1", "Required: %1"},
        {"最新バージョンです", "You have the latest version"},
        {"今すぐ確認", "Check Now"},
        {"ランチャー更新", "Launcher Update"},
        {"バージョン %1: %2", "Version %1: %2"},
        {"必須アップデート", "Mandatory Update"},
        {"安全に利用を続けるにはランチャーの更新が必要です",
         "A launcher update is required to continue safely."},
        {"アップデート", "Update"},
        {"後で", "Later"},
        {"ランチャーを更新してからゲームを操作してください",
         "Update the launcher before operating a game."},
        {"更新と通知", "Updates & Notifications"},
        {"詳細", "Details"},
        {"ランチャーバージョン", "Launcher Version"},
        {"ビルド番号", "Build Number"},
        {"アーキテクチャ", "Architecture"},
        {"ライセンス", "Licenses"},
        {"Qtライブラリ交換手順", "Qt Library Replacement"},
        {"更新履歴", "Update History"},
        {"更新履歴はまだありません", "No update history is available yet."},
        {"プライバシーポリシー", "Privacy Policy"},
        {"利用規約", "Terms of Use"},
        {"診断情報をコピー", "Copy Diagnostics"},
        {"診断情報", "Diagnostics"},
        {"個人パスを除外した診断情報をコピーしました",
         "Diagnostics were copied without personal paths."},
        {"文書を読み込めません", "The document could not be loaded."},
        {"ゲームファイルを検証", "Verify Game Files"},
        {"修復", "Repair"},
        {"インストールフォルダーを開く", "Open Installation Folder"},
        {"ログフォルダーを開く", "Open Log Folder"},
        {"失敗した一時データを削除", "Delete Failed Temporary Data"},
        {"一時データの削除", "Delete Temporary Data"},
        {"未完了のダウンロードデータを削除しますか？", "Delete incomplete download data?"},
        {"ゲームをアンインストール", "Uninstall Game"},
        {"インストール済みですか？ ゲームの場所を特定", "Already installed? Locate the game"},
        {"既存ゲームの場所を選択", "Select existing game location"},
        {"既存ゲームのフォルダーを選択", "Select Existing Game Folder"},
        {"セーブデータフォルダーを開く", "Open Save Data Folder"},
        {"アンインストール", "Uninstall"},
        {"次のゲーム本体を削除します。セーブデータは保持されます。\n\n%1\n%2",
         "The following game files will be removed. Save data will be kept.\n\n%1\n%2"},
        {"ランチャーを表示", "Show Launcher"},
        {"終了", "Exit"},
        {"%1 / %2  %3/s  ファイル %4/%5", "%1 / %2  %3/s  Files %4/%5"},
        {"%1 を次の場所へインストールします。\n\n%2\n\n続行しますか？",
         "%1 will be installed in:\n\n%2\n\nContinue?"},
    };
    return translations.value(QString::fromUtf8(sourceText));
}

} // namespace pandd
